<a href="https://colab.research.google.com/github/mayankgupta5758/localrepo/blob/main/17_NumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Basics

* NumPy stands for Numerical Python and also known as array oriented computing.
* NumPy is a library written for scientific computing and data analysis.
* NumPy consists of a powerful data structure called multidimensional arrays.
* The most basic object in Numpy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why NumPy?
 * convenience & speed

 * NumPy is much faster than the standard python ways to do computations.

 * We don't have to do the explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

 * NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

#### Install numpy library

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


#### Importing numpy library

In [ ]:
import numpy as np

#### creating array using .array() method

In [ ]:
#Ex1)
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [ ]:
# to check the type
type(arr)

numpy.ndarray

#### to get the dimension

In [ ]:
arr.shape

(3,)

#### to get the data types of the array elements

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
#Ex2) 2d array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(3, 3)

In [ ]:
b.dtype

dtype('int32')

In [ ]:
#we have a list
lst_1 = [i for i in range(10)]
lst_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# to add value 2 to all the elements

#1) normal method
# lst_2 = []
# for item in lst_1:
#     lst_2.append(item + 2)
# print(lst_2)

#2) list comprehension
lst_2 = [i+2 for i in lst_1]
print(lst_2)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


#### Numpy will do elementwise calculations

In [ ]:
# arange() is similar to range()
np_arr1 = np.arange(10)
np_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_arr2 = np_arr1 + 2
np_arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Performance measurement

**%timeit** is an python function, which can be used to check the time taken by a particular piece of code (A single execution statement, or a single method)

#### Ex1) Time taken by the normal lists to do a task

In [ ]:
%timeit [i**3 for i in range(10000)]

7.57 ms ± 185 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Time taken by Numpy arrays to do the same task

In [ ]:
%timeit np.arange(10000)**3

53.8 µs ± 3.99 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### Ex2) Time taken to multiply two lists elementwise

In [ ]:
l1 = [i for i in range(10000)]
l2 = [i**2 for i in range(10000)]

In [ ]:
%timeit list(map(lambda x, y: x*y, l1, l2))

2.54 ms ± 207 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Time taken by Numpy arrays to do the same task

In [ ]:
a1 = np.arange(10000)
b1 = np.arange(10000)**2

In [ ]:
%timeit a1*b1

20.2 µs ± 654 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Creating Numpy arrays

#### np.array(list)

In [ ]:
#Ex 1)
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [ ]:
#Ex 2)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


#### np.arange(start,stop,step)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.arange(21,0,-2)

array([21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

#### np.zeros(shape)

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros(1, dtype=np.int32) #vector

array([0])

In [ ]:
np.zeros((1,1), dtype=np.int32) #matrix

array([[0]])

#### np.zeros_like(ndarray)

In [ ]:
a = np.array([[2, 3], [2, 4], [8, 9]])
print(a)
print(a.shape)

[[2 3]
 [2 4]
 [8 9]]
(3, 2)


In [ ]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

#### np.ones(shape)

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones(1, dtype=np.int32) #vector

array([1])

In [ ]:
np.ones((1,1), dtype=np.int32) #matrix

array([[1]])

#### np.ones_like(ndarray)

In [ ]:
a = np.array([[2, 3], [2, 4], [8, 9]])
print(a)
print(a.shape)

[[2 3]
 [2 4]
 [8 9]]
(3, 2)


In [ ]:
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

#### np.full(shape,value)

In [ ]:
np.full((5, 3), 3.3)

array([[3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3]])

In [ ]:
np.full((2, 4),  3.7, dtype=np.int32)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

#### np.eye(m) : this method is used to create identity matrix , here m = n

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(4,dtype=np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### np.diag(list) : is used to create diagonal matrix

In [ ]:
np.diag([2, 5, 68, 78])

array([[ 2,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 68,  0],
       [ 0,  0,  0, 78]])

In [ ]:
np.diag(np.arange(1,16,2))

array([[ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 11,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 15]])

# Accessing and Slicing Numpy array elements

### 1D arrays

In [ ]:
a = np.array([2,4,6,8,10,12,14,16])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
# accessing first element
a[0]

2

In [ ]:
# accessing third element
a[2]

6

In [ ]:
# accessing last element
a[-1]

16

In [ ]:
# accessing multiple elements
a[[0,2,4]]

array([ 2,  6, 10])

In [ ]:
# slicing
# to get all the elements from 2nd index
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [ ]:
# to get all the alternate elements
a[::2]

array([ 2,  6, 10, 14])

### n-dimension array

In [ ]:
# consider we have 2D array
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# to access 10
# a[rowIndex,columnIndex]

a[2,2]

10

In [ ]:
# to access 13
a[3,1]

13

In [ ]:
# to get 0,1,4,5
a[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [ ]:
# to get 10,11,14,15
a[2:,2:]

array([[10, 11],
       [14, 15]])

In [ ]:
# similarly to get 5,6,9,10
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# to check which elements are greater than 5
a>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# to get the elements that are greater than 5
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# to get the elements between 5 to 10
a[(a > 5) & (a < 10)]

array([6, 7, 8, 9])

# Copying and modifying the numpy arrays

In [ ]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b[0] = 100

In [ ]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

##### shares_memory()
this method checks if both the arrays shares the same memory

In [ ]:
np.shares_memory(a,b)

True

#### .copy()

In [ ]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = a.copy()
b

In [ ]:
b[0] = 100

In [ ]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.shares_memory(a,b)

False